[project]
name = "ai-insurance-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.49.1",
    "openai>=2.6.1",
    "schedule>=1.2.2",
]
